### PR TITLE
ft(hotel & resto): hotel and resto

### PR DESCRIPTION
**Pull request by Emile-Nsengimana**
#### What does this PR do?

- register hotel or resto

#### Description of Task to be completed?

- As a resto & hotel client, I would like to be able to see the list of the hotels and resto available on Quicks with a description

acceptance criteria

 - [x] I can see the hotel or resto name
 - [x] I can see a picture of that hotel
 - [x] I can see the description of the hotel or resto through read more
 - [ ] I can see the resto ranking (if applicable)
 - [x] I can see the location of the resto (the smallest location unit) e.g. Gishushu using google pin (but something to consider)

#### How should this be manually tested?

- Clone the project through your terminal(VScode terminal)

      git clone https://github.com/Volve-gitore/quickss-backend.git

- Go to the project and Open the project

       cd quickss-backend && cd .

- Open the feature through its branch

       - git checkout ft-hotels-resto-QUIC-31

- Install all the dependencies

       yarn install

#### Any background context you want to provide?

- remember to check `.example.env` for updated environment variables

#### What are the relevant Jira story?

- [QUIC-31](https://quickss.atlassian.net/browse/QUIC-31)

#### Screenshots (if appropriate)
expected equest & response

Screenshot from 2020-11-05 07-11-41

Tests
Screenshot from 2020-11-05 07-10-45

### CODE REVIEW

**Review by Kagorora — COMMENTED** [review]
@Emile-Nsengimana Good work so far, here are my comments

1. Please add the script to populate the seeds in the database.
seeds

2. Checkout the test(one is failling)
test

3. Please try to be as detailed as possible on your PR.
 It would be much easier to review your work if your PR was very detailed with all the information One needs for a better review, namely:

1. The route to be used
2.  The body of request (if applyied)
3.  The Params/header (if one needs to be logged in or not and other params that might be needed)
4. The Picture (this should be included as It guides the reviewer in your absence)

**Comment by Emile-Nsengimana** [comment]
> @Emile-Nsengimana Good work so far, here are my comments
> 
>     1. Please add the script to populate the seeds in the database.
>        seeds
> 
>     2. Checkout the test(one is failling)
>        test
> 
>     3. Please try to be as detailed as possible on your PR.
>        It would be much easier to review your work if your PR was very detailed with all the information One needs for a better review, namely:
> 
>     4. The route to be used
> 
>     5. The body of request (if applyied)
> 
>     6. The Params/header (if one needs to be logged in or not and other params that might be needed)
> 
>     7. The Picture (this should be included as It guides the reviewer in your absence)

**Review by BlaiseJavan — APPROVED** [review]
You can merge.

**Review by Kagorora — APPROVED** [review]
Please remember, to add the seeding script

**Pull request merged**
